//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITYDOCUMENT
    {
        public int ACTIVITY_CODE { get; set; }
        public int DOCUMENT_CODE { get; set; }
        public Nullable<System.DateTime> DDATE { get; set; }
        public string PATH { get; set; }
        public string FILE_NAME { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<int> TYPE { get; set; }
    }
}
