//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITYPICTURE
    {
        public int ID { get; set; }
        public Nullable<int> ACTIVITY_CODE { get; set; }
        public string PICTURE_NAME { get; set; }
        public Nullable<int> TYPE { get; set; }
    }
}
