//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITYMAPLOCATIONS_silll
    {
        public int ACTIVITY_CODE { get; set; }
        public string GPS_LATITUDE { get; set; }
        public string GPS_LONGITUDE { get; set; }
    }
}
