//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITYMAILREPORT
    {
        public int ROW_NO { get; set; }
        public Nullable<int> MTO { get; set; }
        public Nullable<int> OPER_NO { get; set; }
        public string DESCRIPTION { get; set; }
        public string SQL { get; set; }
        public Nullable<int> MFROM { get; set; }
        public Nullable<int> ISOUTLOOK { get; set; }
    }
}
