//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITYSHELF
    {
        public int ID { get; set; }
        public Nullable<int> ACTIVITY_CODE { get; set; }
        public string RIVAL_COMPANY_NAME { get; set; }
        public string BARCODE { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> FACE { get; set; }
        public string PRO_NAME { get; set; }
        public Nullable<decimal> PRO_PRICE { get; set; }
        public Nullable<System.DateTime> RDATE { get; set; }
        public string SHELF_LABEL { get; set; }
    }
}
