//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDITIONALAREA
    {
        public int COMPANY_CODE { get; set; }
        public int CONTACT_CODE { get; set; }
        public int CODE { get; set; }
        public string TYPE { get; set; }
        public string EXP_TR { get; set; }
        public string EXP_EN { get; set; }
        public string EXP_GR { get; set; }
        public string SVALUE { get; set; }
        public Nullable<int> ORDER_NO { get; set; }
    }
}
