//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BACKGROUNDCOLOR
    {
        public string FORM_NAME { get; set; }
        public Nullable<int> COLOR { get; set; }
        public Nullable<int> USER_CODE { get; set; }
    }
}
