//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR
    {
        public int CONTACT_CODE { get; set; }
        public int COMPANY_CODE { get; set; }
        public int CAR_CODE { get; set; }
        public int TRADEMARK { get; set; }
        public int MODEL { get; set; }
        public System.DateTime PDATE { get; set; }
        public Nullable<int> COLOR { get; set; }
    }
}
