//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANYSOCIALMEDIA
    {
        public int ID { get; set; }
        public Nullable<int> COMPANY_CODE { get; set; }
        public Nullable<int> SOCIAL_MEDIA_TYPE { get; set; }
        public string SOCIAL_MEDIA_LINK { get; set; }
    }
}
