//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANYVALUE
    {
        public int ID { get; set; }
        public int COMPANY_CODE { get; set; }
        public int YEAR { get; set; }
        public Nullable<decimal> V1 { get; set; }
        public Nullable<decimal> V2 { get; set; }
        public Nullable<decimal> V3 { get; set; }
        public Nullable<decimal> V4 { get; set; }
        public Nullable<decimal> V5 { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public System.DateTime LAST_UPDATE { get; set; }
        public string LAST_UPDATE_USER { get; set; }
    }
}
