//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRACT_DETAIL
    {
        public int ID { get; set; }
        public Nullable<int> CONTRACT_ID { get; set; }
        public Nullable<int> TYPE { get; set; }
        public Nullable<int> ROW_ORDER_NO { get; set; }
        public Nullable<float> TOTAL { get; set; }
        public string CUR_TYPE { get; set; }
        public Nullable<float> CUR_VALUE { get; set; }
        public Nullable<float> TOTAL_UPB { get; set; }
        public string EXPLANATION { get; set; }
        public Nullable<float> TAX_PERCENT { get; set; }
        public Nullable<float> TOTAL_UNTAX { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> PAY_DATE { get; set; }
    }
}
