//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRACT
    {
        public int CONTRACT_ID { get; set; }
        public Nullable<int> COMPANY_CODE { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<System.DateTime> SDATE { get; set; }
        public Nullable<System.DateTime> EDATE { get; set; }
        public string DOCUMENT_NO1 { get; set; }
        public Nullable<int> DOCUMENT_NO2 { get; set; }
        public Nullable<int> CONTACT_CODE { get; set; }
        public Nullable<int> OPPORTUNITY_CODE { get; set; }
        public Nullable<float> PRICE { get; set; }
        public string CUR_TYPE { get; set; }
        public Nullable<float> CUR_VALUE { get; set; }
        public Nullable<int> PAYMENT_TYPE { get; set; }
        public string PAYMENT_DES { get; set; }
        public Nullable<int> ADDRESS_ID { get; set; }
        public Nullable<int> UPPER_CONTRACT_CODE { get; set; }
        public Nullable<int> APPOINTED_USER_CODE { get; set; }
        public string LAST_UPDATE_USER { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<float> BUDGET { get; set; }
        public string PARAMETER { get; set; }
        public Nullable<int> EXPENSE_INCLUDE { get; set; }
        public Nullable<int> TYPE { get; set; }
    }
}
