//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATABASEUPDATE
    {
        public int VeriTabaniVersiyon_ID { get; set; }
        public Nullable<int> VersiyonNo { get; set; }
        public Nullable<System.DateTime> GuncellemeZamani { get; set; }
    }
}
