//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTEGRATION
    {
        public int ROW_ORDER_NO { get; set; }
        public string PROGRAM_NAME { get; set; }
        public Nullable<int> PROGRAM_OPER_NO { get; set; }
        public string OPERATION_TYPE { get; set; }
        public string EXE_NAME { get; set; }
        public string COM_LINE { get; set; }
    }
}
