//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENVIRONMENT
    {
        public int ACTIVITY_POLL { get; set; }
        public Nullable<int> ACTIVITY_APPOROVMENT { get; set; }
        public Nullable<int> BILL_LEVEL { get; set; }
        public Nullable<int> STOK_OUTSIDE { get; set; }
        public string LAST_UPDATE_USER { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<int> UPPER_COMPANY_INFORMATION { get; set; }
        public Nullable<int> ACTIVITY_POLLCC { get; set; }
        public string ENVPAR { get; set; }
        public string NM { get; set; }
        public string ACT1 { get; set; }
        public string ACT2 { get; set; }
        public string INCOMING_MAIL_SERVER { get; set; }
        public string OUTGOING_MAIL_SERVER { get; set; }
        public string POP3_PORT { get; set; }
        public string SMTP_PORT { get; set; }
        public string SSL { get; set; }
        public Nullable<int> LEVEL_ACTIVE { get; set; }
        public Nullable<int> DECIMAL { get; set; }
    }
}
