//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXCELD1
    {
        public int CODE { get; set; }
        public string EXPLANATION { get; set; }
        public string FPATH { get; set; }
        public string FORM_NAME { get; set; }
        public string CONTROL_NAME { get; set; }
        public string CONTROL_TYPE { get; set; }
        public string CONTROL_PROPERTY { get; set; }
        public string CONTROL_VISIBLE { get; set; }
        public string GRID_COL_VISIBLE { get; set; }
        public string HIDDEN_CONTROL_VISIBLE { get; set; }
        public string HIDDEN_FIELD_VISIBLE { get; set; }
        public string ROW { get; set; }
        public string COL { get; set; }
        public Nullable<int> ROWORDERNO { get; set; }
        public string MSQL { get; set; }
        public Nullable<int> TYPE { get; set; }
        public Nullable<int> MCAL { get; set; }
        public Nullable<int> PDFCOLW { get; set; }
        public string R_ID { get; set; }
        public string B_CONTROL_NAME { get; set; }
        public Nullable<int> COMBO_ROW_NO { get; set; }
        public Nullable<int> COMBO_GROUP_NO { get; set; }
        public Nullable<int> PDFCOL { get; set; }
        public string SAVE_FILE_TODB { get; set; }
    }
}
