//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXCELD
    {
        public int CODE { get; set; }
        public int TYPE { get; set; }
        public Nullable<int> R_ID { get; set; }
        public string SQL { get; set; }
    }
}
