//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPENSEDETAIL
    {
        public int ID { get; set; }
        public Nullable<int> EXPENSE_CODE { get; set; }
        public Nullable<int> ROW_ORDER_NO { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<int> COMPANY_CODE { get; set; }
        public string STOK_CODE { get; set; }
        public string PRODUCT_NAME { get; set; }
        public Nullable<int> PROJECT_CODE { get; set; }
        public Nullable<int> CONTRACT_CODE { get; set; }
        public Nullable<System.DateTime> DOCUMENT_DATE { get; set; }
        public Nullable<int> EXPENSE_TYPE { get; set; }
        public string EXPENSE_NO { get; set; }
        public Nullable<float> TOTAL_UPBTAX { get; set; }
        public Nullable<float> TOTAL_UPB { get; set; }
        public Nullable<float> CUR { get; set; }
        public string CUR_TYPE { get; set; }
        public Nullable<float> TOTAL { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public string LAST_UPDATE_USER { get; set; }
        public string EXPLANATION { get; set; }
    }
}
