//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIHRIST
    {
        public int FIH_NO { get; set; }
        public string MENU_ADI { get; set; }
        public string FIH_SQL { get; set; }
        public int ROW_ORDER { get; set; }
        public Nullable<int> R_ID { get; set; }
    }
}
