//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIHRISTD
    {
        public int FIH_NO { get; set; }
        public string BASLIK { get; set; }
        public string KOLON_ADI { get; set; }
        public Nullable<int> VERI_TIPI { get; set; }
        public Nullable<int> ARAMA_VAR { get; set; }
        public Nullable<int> VARSAYILAN_ARAMA { get; set; }
        public Nullable<int> KOLON_ENI { get; set; }
        public int ORDER_NO { get; set; }
        public string WILL_BE_RETURN { get; set; }
        public Nullable<int> R_ID { get; set; }
    }
}
