//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMREPLACMENT
    {
        public string FORM_NAME { get; set; }
        public string CONTROL_NAME { get; set; }
        public string AREA_NAME { get; set; }
        public int ORDER_NO { get; set; }
        public Nullable<int> MWIDTH { get; set; }
        public int USER_CODE { get; set; }
        public Nullable<int> TYPE { get; set; }
        public string CONTROL_TYPE { get; set; }
        public string CONTROL_VISIBLE { get; set; }
        public Nullable<decimal> LOCATION_X { get; set; }
        public Nullable<decimal> LOCATION_Y { get; set; }
        public Nullable<int> CONTROL_WIDTH { get; set; }
        public Nullable<int> CONTROL_HEIGHT { get; set; }
        public string TEXT_VISIBLE { get; set; }
        public Nullable<decimal> TEXT_WIDTH { get; set; }
        public Nullable<int> TEXT_FORE_COLOR { get; set; }
        public string CAPTION_VISIBLE { get; set; }
        public Nullable<decimal> CAPTION_WIDTH { get; set; }
        public Nullable<int> CAPTION_FORE_COLOR { get; set; }
        public string FNO { get; set; }
        public string RNO { get; set; }
        public string BUTTON_VISIBLE { get; set; }
        public Nullable<decimal> BUTTON_WIDTH { get; set; }
        public string EXP_VISIBLE { get; set; }
        public Nullable<int> EXP_TEXT_WIDTH { get; set; }
        public Nullable<int> EXP_FORE_COLOR { get; set; }
        public Nullable<int> TAB_INDEX { get; set; }
        public string MULTILINE { get; set; }
        public string TAG { get; set; }
        public string EXT1 { get; set; }
        public string EXT2 { get; set; }
        public string TEXTDATATYPE { get; set; }
        public string TEXTREADONLY { get; set; }
    }
}
