//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMADDITIONALAREAVALUE
    {
        public string FORM_NAME { get; set; }
        public int CODE { get; set; }
        public string VERSION { get; set; }
        public string TXTAKTIVITEALAN1 { get; set; }
        public string ALI { get; set; }
        public Nullable<System.DateTime> TXTTIME { get; set; }
        public string ALPERXXX { get; set; }
        public string EK1 { get; set; }
        public string FIMAYENIALAN { get; set; }
        public int ROW_NO { get; set; }
        public string MAKINEADI { get; set; }
        public Nullable<System.DateTime> TXTMYDATE { get; set; }
        public string CHKVARMI { get; set; }
        public string TXTADET_96_1 { get; set; }
        public Nullable<int> LAST_UPDATE_USER { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public string FIRMAYAPISI { get; set; }
        public string ALTSEKTOR { get; set; }
        public string FIRMA_KISA_ADI { get; set; }
        public string FIRMA_DEPARTMANI { get; set; }
        public string CALISAN_SAYISI { get; set; }
        public string REFERANS_KISI { get; set; }
        public string MARKALARI { get; set; }
        public string CONTACT_DOGUM_YERI { get; set; }
        public string CONTACT_DOGUM_ILI { get; set; }
        public string CONTACT_DOGUM_ILCESI { get; set; }
        public string CONTACT_GERCEK_UNVAN { get; set; }
        public string CONTACT_BIZIMLE_ILISKISI { get; set; }
        public string CONTACT_POZISYONU { get; set; }
        public string CONTACT_LISE { get; set; }
        public string FIRMA_VERILEN_HIZMET_ALAN { get; set; }
        public string FIRMA_PROJE_BILGISI { get; set; }
        public string KISI_YENI_FIRMA_BILGISI { get; set; }
        public string FIRSAT_MEVCUT_MUSTERI { get; set; }
        public string FIRSAT_VERILEN_HIZMETLER { get; set; }
        public string FIRSAT_KIMDEN_GELDI { get; set; }
        public string FIRSATIN_BIZE_ULASMA_SEKLI { get; set; }
        public string TEKLIF_KAZANMA_YUZDESI { get; set; }
        public string EVRAK_KAZANDIK_REFERANS_NOTU { get; set; }
        public string EVRAK_ERTELENDI_NOTU { get; set; }
        public Nullable<System.DateTime> EVRAK_ERTELENME_TARIHI { get; set; }
        public string CONTACT_DOGDUGU_ULKE { get; set; }
        public string KISI_UYE_DERNEKLER { get; set; }
    }
}
