//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMADDITIONALAREA
    {
        public string FORM_NAME { get; set; }
        public string CONTROL_NAME { get; set; }
        public string CONTROL_TYPE { get; set; }
        public string CONTAINER_CONTROL_NAME { get; set; }
    }
}
