//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMDESIGNERRELATION
    {
        public int PROGRAM_CODE { get; set; }
        public string FORM_CODE { get; set; }
        public int MTYPE { get; set; }
    }
}
