//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTP
    {
        public int CODE { get; set; }
        public int ROW_NO { get; set; }
        public string FTP_ADDRESS { get; set; }
        public string FTP_USER_NAME { get; set; }
        public string FTP_PASSWORD { get; set; }
        public string DB_NAME { get; set; }
        public string DB_USER_NAME { get; set; }
        public string DB_PASSWORD { get; set; }
        public string LOCAL_PATH { get; set; }
    }
}
