//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRIDDESIGNE
    {
        public string FORM_NAME { get; set; }
        public int ISBASE { get; set; }
        public string COLUMN_NAME { get; set; }
        public int USER_CODE { get; set; }
        public Nullable<int> R_ID { get; set; }
        public string ISVISIBLE { get; set; }
        public string FIELD_NAME { get; set; }
        public string DATA_TYPE { get; set; }
        public string READ_ONLY { get; set; }
        public string SELECT_FIELD_NAME { get; set; }
        public Nullable<int> TYPE { get; set; }
    }
}
