//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUPMULTI
    {
        public int ID { get; set; }
        public string CODE_NAME { get; set; }
        public int CODE { get; set; }
        public int GROUP_CODE { get; set; }
        public int ROW_ORDER_NO { get; set; }
    }
}
