//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEVEL
    {
        public int LEVEL_CODE { get; set; }
        public string LEVEL_NAME { get; set; }
        public string CUR_TYPE { get; set; }
        public Nullable<float> CUR_VALUE { get; set; }
        public Nullable<float> HOURLY_SALARY { get; set; }
        public Nullable<int> DEPARTMAN { get; set; }
    }
}
