//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICENSE_PLATE
    {
        public int ID { get; set; }
        public string EXPENSE_CODE { get; set; }
        public string LICENSE_PLATE1 { get; set; }
        public Nullable<System.DateTime> SDATE { get; set; }
        public Nullable<System.DateTime> EDATE { get; set; }
        public Nullable<int> KM { get; set; }
        public Nullable<float> TOTAL { get; set; }
        public string CUR_TYPE { get; set; }
        public Nullable<float> CUR_VALUE { get; set; }
        public Nullable<float> TOTAL_UPB { get; set; }
        public Nullable<int> TOTAL_MONTH { get; set; }
        public string LAST_UPDATE_USER { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<int> COMPANY_CODE { get; set; }
        public Nullable<int> OPPORTUNITY_CODE { get; set; }
    }
}
