//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        public string CUSTOMER_CODE { get; set; }
        public string DB_NAME { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string MAIN_SERVER { get; set; }
        public string LOGIN_CODE { get; set; }
    }
}
