//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MACHINEPARK
    {
        public int CODE { get; set; }
        public string MACHINE_CODE { get; set; }
        public int COMPANY_CODE { get; set; }
        public Nullable<int> NAME { get; set; }
        public string MODEL { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> EXTRA { get; set; }
        public Nullable<int> TYPE1 { get; set; }
        public Nullable<int> TYPE2 { get; set; }
        public Nullable<int> TYPE3 { get; set; }
        public Nullable<int> TYPE4 { get; set; }
        public Nullable<int> TYPE5 { get; set; }
        public string LAST_UPDATE_USER { get; set; }
        public System.DateTime LAST_UPDATE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<int> AMOUNTANDEXTRA { get; set; }
        public string MACHINE_UPPER_CODE { get; set; }
    }
}
