//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAPLOCATION
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> USER_CODE { get; set; }
        public Nullable<int> COMPANY_CODE { get; set; }
        public string GPS_LATITUDE { get; set; }
        public string GPS_LONGITUDE { get; set; }
        public Nullable<int> DURATION { get; set; }
        public string EXP { get; set; }
    }
}
