//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENUD
    {
        public string MENU_NAME { get; set; }
        public string CONTROL_NAME { get; set; }
        public string ISVISIBLE { get; set; }
        public string FILE_NAME { get; set; }
        public byte[] BFILE { get; set; }
        public Nullable<int> FILE_SIZE { get; set; }
        public Nullable<int> USER_CODE { get; set; }
    }
}
