//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENUEXE
    {
        public Nullable<int> CODE { get; set; }
        public string MENU_NAME { get; set; }
        public string CONTROL_NAME { get; set; }
        public string EXE_NANE { get; set; }
        public Nullable<int> EXE_TYPE { get; set; }
        public string MSQL { get; set; }
        public Nullable<int> SEND_COM_PAR { get; set; }
        public Nullable<int> R_ID { get; set; }
    }
}
