//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENULOAD
    {
        public int ID { get; set; }
        public string MENU_NAME { get; set; }
        public string LINK { get; set; }
        public Nullable<int> LANGUAGE { get; set; }
        public Nullable<int> USER_CODE { get; set; }
        public Nullable<int> RES_ID { get; set; }
        public Nullable<int> ORDER_BY { get; set; }
        public Nullable<int> VISIBLE { get; set; }
        public Nullable<int> TYPE { get; set; }
    }
}
