//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPPORTUNITYDETAILVERSIONADDAREA
    {
        public int OPPORTUNITY_CODE { get; set; }
        public int ROW_ORDER_NO { get; set; }
        public string VERSION { get; set; }
        public string C1 { get; set; }
        public string C2 { get; set; }
        public string PLAKA { get; set; }
        public string SASE { get; set; }
    }
}
