//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPPORTUNITYHISTORY
    {
        public int ID { get; set; }
        public Nullable<int> OPPORTUNITY_CODE { get; set; }
        public Nullable<int> LAST_DOCUMENT_TYPE { get; set; }
        public Nullable<int> ACTUEL_DOCUMENT_TYPE { get; set; }
        public Nullable<int> LAST_UPDATE_USER { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
    }
}
