//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPPORTUNITYMASTER
    {
        public OPPORTUNITYMASTER()
        {
            this.OPPORTUNITYDETAILs = new HashSet<OPPORTUNITYDETAIL>();
            this.STOKACTUALORDERs = new HashSet<STOKACTUALORDER>();
        }
    
        public int OPPORTUNITY_CODE { get; set; }
        public string VERSION { get; set; }
        public int CONTACT_CODE { get; set; }
        public int COMPANY_CODE { get; set; }
        public Nullable<int> DOCUMENT_TYPE { get; set; }
        public string DOCUMENT_NO1 { get; set; }
        public string CERTIFICATE_NO { get; set; }
        public Nullable<int> NORMAL_BACK { get; set; }
        public Nullable<int> SELLING_BUYING { get; set; }
        public Nullable<int> PROCESS_TYPE { get; set; }
        public string CURRENT_CODE { get; set; }
        public string CURRENT_NAME { get; set; }
        public Nullable<System.DateTime> DOCUMENT_DATE { get; set; }
        public Nullable<System.DateTime> CERTIFICATE_DATE { get; set; }
        public Nullable<int> OPEN_CLOSE { get; set; }
        public Nullable<System.DateTime> PEYMENT_TERM { get; set; }
        public Nullable<int> PAYMENT_TYPE { get; set; }
        public Nullable<int> WAREHOUSE { get; set; }
        public Nullable<int> REPRESENT { get; set; }
        public Nullable<int> CATEGORY { get; set; }
        public Nullable<int> SEARCH_METHOD { get; set; }
        public Nullable<int> SEARCH_STEP { get; set; }
        public Nullable<int> REVISION { get; set; }
        public Nullable<int> FORM_NO { get; set; }
        public Nullable<int> PROJECT_CODE { get; set; }
        public Nullable<int> WINNER_COMPANY_CODE { get; set; }
        public Nullable<int> LAST_POSITION { get; set; }
        public string WHY_LOST { get; set; }
        public Nullable<int> APPOINTED_USER_CODE { get; set; }
        public string LAST_UPDATE_USER { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<int> WE_WIN { get; set; }
        public Nullable<float> TOTAL_UPB { get; set; }
        public string FREE_STOK { get; set; }
        public Nullable<int> SECTION_CODE { get; set; }
        public Nullable<int> BANK_CODE { get; set; }
        public Nullable<int> CASH_CODE { get; set; }
        public string DOCUMENT_NO2 { get; set; }
        public string EXPLANATION { get; set; }
        public Nullable<int> GROUPS { get; set; }
        public Nullable<int> DELIVERY_TYPE { get; set; }
        public Nullable<float> DISCONT { get; set; }
        public Nullable<float> TRANSPORT { get; set; }
        public Nullable<float> INSURANCE { get; set; }
        public Nullable<float> TAX { get; set; }
        public Nullable<float> TOTAL { get; set; }
        public Nullable<System.DateTime> AVAILABLE_DATE { get; set; }
        public Nullable<int> EXT01 { get; set; }
        public Nullable<int> TRANSPORT_FIRM { get; set; }
        public string TRANSPORT_CUR_TYPE { get; set; }
        public Nullable<float> TRANSPORT_UPBK { get; set; }
        public string INSURANCE_CUR_TYPE { get; set; }
        public Nullable<float> INSURANCE_UPBK { get; set; }
        public string DISCONT_CUR_TYPE { get; set; }
        public Nullable<float> DISCONT_FPB { get; set; }
        public string APPROVMENT_STATUS { get; set; }
        public Nullable<int> SOURCE_CODE { get; set; }
    
        public virtual ICollection<OPPORTUNITYDETAIL> OPPORTUNITYDETAILs { get; set; }
        public virtual ICollection<STOKACTUALORDER> STOKACTUALORDERs { get; set; }
    }
}
