//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFORM
    {
        public string FORM_ID { get; set; }
        public int ID { get; set; }
        public int GROUP_ID { get; set; }
        public string SQL_ID { get; set; }
        public string CONTROL_NAME { get; set; }
        public string CONTROL_VALUE { get; set; }
        public string DATA_TYPE { get; set; }
        public string EVENT { get; set; }
        public string EMPTY_ACTION { get; set; }
        public string CONTROL_INFO { get; set; }
    }
}
