//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIVOTROW
    {
        public int ROW_NO { get; set; }
        public int SQL_ID { get; set; }
        public string ROW { get; set; }
        public string LAN_CODE { get; set; }
    }
}
