//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVENUEMASTER
    {
        public int REVENUE_CODE { get; set; }
        public int COMPANY_CODE { get; set; }
        public int USER_CODE { get; set; }
        public Nullable<int> OPEN_CLOSE { get; set; }
        public string DOCUMENT_NO { get; set; }
        public string CERTIFICATE_NO { get; set; }
        public Nullable<System.DateTime> DOCUMENT_DATE { get; set; }
        public Nullable<System.DateTime> CERTIFICATE_DATE { get; set; }
        public Nullable<decimal> GRAND_TOTAL { get; set; }
        public string LAST_UPDATE_USER { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<int> OPPORTUNITY_CODE { get; set; }
        public Nullable<int> SELLING_BUYING { get; set; }
        public string DOCUMENT_NO2 { get; set; }
        public string EXPLANATION { get; set; }
    }
}
