//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVENUEDETAIL
    {
        public int REVENUE_CODE { get; set; }
        public int ROW_ORDER_NO { get; set; }
        public int USER_CODE { get; set; }
        public int APPROVAL { get; set; }
        public Nullable<int> PAYMENT_TYPE_CODE { get; set; }
        public Nullable<System.DateTime> PAYMENT_DATE { get; set; }
        public Nullable<int> BANK_CODE { get; set; }
        public Nullable<int> CASH_CODE { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public Nullable<int> INSTALLMENT { get; set; }
        public string EXPLANATION { get; set; }
        public string LAST_UPDATE_USER { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public string CUR_TYPE { get; set; }
        public Nullable<decimal> CUR_VALUE { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> TOTAL_UPBK { get; set; }
    }
}
