//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RU
    {
        public int ACTIVITY_CODE { get; set; }
        public int CONTACT_CODE { get; set; }
        public int COMPANY_CODE { get; set; }
        public string FORM_NO { get; set; }
        public string LAST_UPDATE_USER { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> ALIM_TARIHI { get; set; }
        public string RAKIP_FIRMA_ADI { get; set; }
        public string MODELI { get; set; }
        public Nullable<decimal> IGNE_SAYISI { get; set; }
        public Nullable<decimal> ADET { get; set; }
    }
}
