//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_ORI2
    {
        public string DOCUMENT_NO1 { get; set; }
        public System.DateTime DOCUMENT_DATE { get; set; }
        public string STOK_CODE { get; set; }
        public Nullable<float> QUANTITY { get; set; }
        public Nullable<float> QUANTITY_C { get; set; }
        public string UNIT { get; set; }
        public Nullable<float> QUANTITY_OF_PACKET { get; set; }
        public Nullable<float> DAMAGED_QUANTITY { get; set; }
        public Nullable<float> DAMAGED_QUANTITY_C { get; set; }
        public string DAMAGED_UNIT { get; set; }
        public string DAMAGED_EXP { get; set; }
        public Nullable<float> MIS_QUANTITY { get; set; }
        public Nullable<float> MIS_QUANTITY_C { get; set; }
        public string MIS_UNIT { get; set; }
        public string MIS_EXP { get; set; }
        public Nullable<float> EXTRA_QUANTITY { get; set; }
        public Nullable<float> EXTRA_QUANTITY_C { get; set; }
        public string EXTRA_UNIT { get; set; }
        public string EXTRA_EXP { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public string COMPANY_COMMERCIAL_CODE { get; set; }
    }
}
