//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SELLER_BALANCE
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> INVOICE_DATE { get; set; }
        public string INVOICE_NO { get; set; }
        public Nullable<int> OPPORTUNITY_CODE { get; set; }
        public string OPPORTUNITY_EXPLANATION { get; set; }
        public Nullable<int> COMPANY_CODE { get; set; }
        public string COMPANY_NAME { get; set; }
        public Nullable<float> TOTAL_INVOICE { get; set; }
        public Nullable<float> TOTAL_INVOICE_SELLER { get; set; }
        public Nullable<float> COLLECTED { get; set; }
        public Nullable<float> TOTAL_COMMISSION { get; set; }
        public Nullable<float> TOTAL_COMMISSION_PAYMENT { get; set; }
        public Nullable<float> TOTAL_COMMISSION_REMAINING { get; set; }
        public Nullable<float> TOTAL_COMMISSION_INVOICE_EXPECTED { get; set; }
        public Nullable<int> OPPOINTED_USER_CODE { get; set; }
    }
}
