//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SELLER_DETAIL
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DOCUMENT_DATE { get; set; }
        public string DOCUMENT_NO { get; set; }
        public string DOCUMENT_DESCRIPTION { get; set; }
        public Nullable<int> OPPORTUNTIY_CODE { get; set; }
        public Nullable<float> DOCUMENT_TOTAL_DEBIT { get; set; }
        public Nullable<float> DOCUMENT_TOTAL_CREDIT { get; set; }
        public Nullable<float> SELLER_BALANCE { get; set; }
        public Nullable<int> APPOINTED_USER_CODE { get; set; }
    }
}
