//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPEC
    {
        public int CODE { get; set; }
        public string STOK_CODE { get; set; }
        public int ORDER_NO { get; set; }
        public string EXPLANATION { get; set; }
        public string V1 { get; set; }
        public Nullable<int> C1 { get; set; }
        public Nullable<int> M1 { get; set; }
        public Nullable<int> FZ1 { get; set; }
        public Nullable<int> B1 { get; set; }
        public Nullable<int> IT1 { get; set; }
        public string V2 { get; set; }
        public Nullable<int> C2 { get; set; }
        public Nullable<int> M2 { get; set; }
        public Nullable<int> FZ2 { get; set; }
        public Nullable<int> B2 { get; set; }
        public Nullable<int> IT2 { get; set; }
        public string V3 { get; set; }
        public Nullable<int> C3 { get; set; }
        public Nullable<int> M3 { get; set; }
        public Nullable<int> FZ3 { get; set; }
        public Nullable<int> B3 { get; set; }
        public Nullable<int> IT3 { get; set; }
        public string V4 { get; set; }
        public Nullable<int> C4 { get; set; }
        public Nullable<int> M4 { get; set; }
        public Nullable<int> FZ4 { get; set; }
        public Nullable<int> B4 { get; set; }
        public Nullable<int> IT4 { get; set; }
        public string V5 { get; set; }
        public Nullable<int> C5 { get; set; }
        public Nullable<int> M5 { get; set; }
        public Nullable<int> FZ5 { get; set; }
        public Nullable<int> B5 { get; set; }
        public Nullable<int> IT5 { get; set; }
        public string V6 { get; set; }
        public Nullable<int> C6 { get; set; }
        public Nullable<int> M6 { get; set; }
        public Nullable<int> FZ6 { get; set; }
        public Nullable<int> B6 { get; set; }
        public Nullable<int> IT6 { get; set; }
        public string V7 { get; set; }
        public Nullable<int> C7 { get; set; }
        public Nullable<int> M7 { get; set; }
        public Nullable<int> FZ7 { get; set; }
        public Nullable<int> B7 { get; set; }
        public Nullable<int> IT7 { get; set; }
        public string V8 { get; set; }
        public Nullable<int> C8 { get; set; }
        public Nullable<int> M8 { get; set; }
        public Nullable<int> FZ8 { get; set; }
        public Nullable<int> B8 { get; set; }
        public Nullable<int> IT8 { get; set; }
        public string V9 { get; set; }
        public Nullable<int> C9 { get; set; }
        public Nullable<int> M9 { get; set; }
        public Nullable<int> FZ9 { get; set; }
        public Nullable<int> B9 { get; set; }
        public Nullable<int> IT9 { get; set; }
        public string V10 { get; set; }
        public Nullable<int> C10 { get; set; }
        public Nullable<int> M10 { get; set; }
        public Nullable<int> FZ10 { get; set; }
        public Nullable<int> B10 { get; set; }
        public Nullable<int> IT10 { get; set; }
        public string LAST_UPDATE_USER { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public string LAN_CODE { get; set; }
        public Nullable<int> RH { get; set; }
    }
}
