//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPECDESCIRIPTION
    {
        public string STOK_CODE { get; set; }
        public int ROW_ORDER_NO { get; set; }
        public string EXP_TR { get; set; }
        public string EXP_EN { get; set; }
        public string EXP_GR { get; set; }
        public string BOLD { get; set; }
        public string ITALIC { get; set; }
        public string FONT { get; set; }
        public Nullable<int> LOCATION_Y { get; set; }
        public Nullable<int> LOCATION_X { get; set; }
        public string LEFT_TO_RIGHT { get; set; }
        public string UPPER_COLOR_CODE { get; set; }
        public Nullable<int> FONT_SIZE { get; set; }
    }
}
