//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOKWAREHOUSE
    {
        public STOKWAREHOUSE()
        {
            this.STOKACTUALs = new HashSet<STOKACTUAL>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
    
        public virtual ICollection<STOKACTUAL> STOKACTUALs { get; set; }
    }
}
