//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOKCARDUSERPRICE
    {
        public int ID { get; set; }
        public Nullable<int> USER_CODE { get; set; }
        public Nullable<int> STOK_ID { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string CUR_TYPE { get; set; }
        public Nullable<int> PRICE_TYPE { get; set; }
    }
}
