//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOKCARDPICTURE
    {
        public int ID { get; set; }
        public int STOK_ID { get; set; }
        public Nullable<int> ROW_NO { get; set; }
        public string PATH { get; set; }
        public Nullable<int> TYPE { get; set; }
        public Nullable<int> COLOR_CODE { get; set; }
    
        public virtual STOKCARD STOKCARD { get; set; }
    }
}
