//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOKCARD1
    {
        public string CODE { get; set; }
        public string UPPER_CODE { get; set; }
        public string NAME_TR { get; set; }
        public string NAME_EN { get; set; }
        public string NAME_GR { get; set; }
        public Nullable<int> UNIT { get; set; }
        public Nullable<decimal> TAX { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public string CUR_TYPE { get; set; }
        public string LAST_UPDATE_USER { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public string DES_TR { get; set; }
        public string DES_EN { get; set; }
        public string DES_OT { get; set; }
        public string NAME_SHORT { get; set; }
        public string ISHIDDEN { get; set; }
        public string SPECIAL_CODE1 { get; set; }
        public string SPECIAL_CODE2 { get; set; }
        public string SPECIAL_CODE3 { get; set; }
        public Nullable<int> TYPE { get; set; }
        public string MANUFACTURER_PRODUCT_CODE { get; set; }
        public string MANUFACTURER_COMPANY_CODE { get; set; }
        public string DETAILS_FOLLOW { get; set; }
        public string UNIT1_NAME { get; set; }
        public Nullable<float> UNIT1_MULTIPLIER { get; set; }
        public Nullable<float> UNIT1_WEIGHT { get; set; }
        public Nullable<float> UNIT1_WIDTH { get; set; }
        public Nullable<float> UNIT1_LENGTH { get; set; }
        public Nullable<float> UNIT1_HEIGHT { get; set; }
        public Nullable<float> UNIT1_TARE { get; set; }
        public Nullable<float> UNIT2_NAME { get; set; }
        public Nullable<float> UNIT2_MULTIPLIER { get; set; }
        public Nullable<float> UNIT2_WEIGHT { get; set; }
        public Nullable<float> UNIT2_WIDTH { get; set; }
        public Nullable<float> UNIT2_LENGTH { get; set; }
        public Nullable<float> UNIT2_HEIGHT { get; set; }
        public Nullable<float> UNIT2_TARE { get; set; }
        public Nullable<int> MIN_QUANTITY { get; set; }
        public Nullable<int> MAX_QUANTITY { get; set; }
        public Nullable<float> ORDER_QUANTITY { get; set; }
        public Nullable<float> RETAIL_TAX { get; set; }
        public Nullable<float> BULK_TAX { get; set; }
        public string CATEGORY_CODE { get; set; }
        public string MAIN_GRUP { get; set; }
        public string SUB_GRUP1 { get; set; }
        public string SUB_GRUP2 { get; set; }
        public Nullable<int> SECTOR_CODE { get; set; }
        public string RAYON_CODE { get; set; }
        public string PACK_CODE { get; set; }
        public string BRAND_CODE { get; set; }
        public string BODY_CODE { get; set; }
        public string COLOR_CODE { get; set; }
        public string MODEL_CODE { get; set; }
        public string SEASON_CODE { get; set; }
        public Nullable<float> ACTIVE_COST { get; set; }
        public string ACTIVE_COST_CURRENCY { get; set; }
        public Nullable<float> PURCHASE_PRICE { get; set; }
        public Nullable<float> PURCHASE_CURRENCY { get; set; }
        public Nullable<float> SALES_PRICE { get; set; }
        public Nullable<float> SALES_CURRENCY { get; set; }
        public byte[] PICTURE1 { get; set; }
        public byte[] PICTURE2 { get; set; }
        public byte[] PICTURE3 { get; set; }
        public byte[] PICTURE4 { get; set; }
        public string BARCODE_01 { get; set; }
        public string BARCODE_02 { get; set; }
        public string BARCODE_03 { get; set; }
        public string WEB_TRANSFER { get; set; }
        public string ISACTIVE { get; set; }
        public Nullable<int> MAXLOAD { get; set; }
        public Nullable<byte> MAXHEIGHT { get; set; }
        public Nullable<byte> MAXBOM { get; set; }
    }
}
