//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFILE
    {
        public int FILE_CODE { get; set; }
        public string DOCUMENT_TYPE { get; set; }
        public string PROGRAM_NAME { get; set; }
        public Nullable<int> CONTACT_CODE { get; set; }
        public Nullable<int> COMPANY_CODE { get; set; }
        public string DOCUMENT_DESCRIPTION { get; set; }
        public string FILE_NAME { get; set; }
        public byte[] BFILE { get; set; }
        public string FILE_TYPE { get; set; }
        public Nullable<int> FILE_SIZE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<int> ACTIVITY_CODE { get; set; }
        public string LAN_CODE { get; set; }
        public string VERSION { get; set; }
    }
}
