//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSFER
    {
        public int SQL_ID { get; set; }
        public int TYPE_ID { get; set; }
        public string SQL { get; set; }
        public string UPDATE_TABLE { get; set; }
        public string UPDATE_FIELD { get; set; }
        public string CONDITION { get; set; }
        public Nullable<int> LENGTH { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
