//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSFERUSER
    {
        public int USER_CODE { get; set; }
        public string SERVER_PATH { get; set; }
        public Nullable<int> IS_ACTIVE { get; set; }
        public Nullable<int> IS_SERVER { get; set; }
        public string LOCAL_IN { get; set; }
        public string LOCAL_OUT { get; set; }
        public string FTP_ADDRESS_IN { get; set; }
        public string FTP_ADDRESS_OUT { get; set; }
        public string FTP_USER_NAME { get; set; }
        public string FTP_PASSWORD { get; set; }
        public string VPN_IN { get; set; }
        public string VPN_OUT { get; set; }
    }
}
