//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERRIGHTBASE
    {
        public string MENU_NAME { get; set; }
        public string MAIN { get; set; }
        public string NODE_NO { get; set; }
        public string OBJECT_NAME { get; set; }
        public Nullable<int> P_NECESSARY { get; set; }
        public Nullable<int> R_ID { get; set; }
        public Nullable<int> ORDER_NO { get; set; }
        public Nullable<int> OPER_NO { get; set; }
        public Nullable<int> WINDOWSTATE { get; set; }
        public string SHORT_CUT_KEY { get; set; }
    }
}
