//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMMAILFILEREPORT
    {
        public int ROW_NO { get; set; }
        public string MAIL_TO { get; set; }
        public string PATH { get; set; }
        public string FILES_FILTER { get; set; }
        public string BACKUP_PATH { get; set; }
        public string SUBJECT { get; set; }
        public string BADY { get; set; }
    }
}
